models/UserLicense.php
<?php

namespace app\models;

use Yii;
use yii\db\ActiveRecord;
use yii\behaviors\TimestampBehavior;
use yii\behaviors\BlameableBehavior;
use app\components\behaviors\ActivityLogBehaviorUser;
use yii\web\UploadedFile;

/**
* This is the model class for table "{{%user_license}}".
*
* @property integer $id
* @property integer $user_id
* @property integer $city_id
* @property string $license_image
* @property string $license_start
* @property string $license_expiry
* @property string $reminder_sent
*/
class UserLicense extends ActiveRecord
{
  public $imageFile,$oldImage;
  public $allowedImageSize = 1048576;
  public $allowedImageTypes=['jpg', 'jpeg', 'png', 'gif', 'JPG', 'JPEG', 'PNG', 'GIF'];
  /**
  * @inheritdoc
  */
  public static function tableName()
  {
    return '{{%user_license}}';
  }

  /**
  * @inheritdoc
  */
  public function rules()
  {
    return [
      [['user_id','city_id','license_start','license_expiry'],'required'],
      [['user_id','city_id','reminder_sent','created_by','updated_by','trashed','trashed_by'],'integer'],
      [['license_start','license_expiry'],'string'],
      [['reminder_sent_date'],'safe'],
      [['license_expiry'],'checkStartEnd'],
      [['license_expiry'],'checkDuplicate'],
      [['license_image'], 'file', 'extensions'=>implode(",",$this->allowedImageTypes), 'maxSize' => $this->allowedImageSize, 'tooBig' => 'Image is too big, Maximum allowed size is 1MB']
    ];
  }

  /**
  * Validates the if its overlaping or duplicate.
  * @param string $attribute the attribute currently being validated
  * @param array $params the additional name-value pairs given in the rule
  */
  public function checkStartEnd($attribute, $params)
  {
    if (!$this->hasErrors()) {
      if($this->license_start!=null && $this->license_start>$this->license_expiry){
        $this->addError($attribute, 'Please provide valid start and expiry dates');
      }
    }
  }

  /**
  * Validates the if its overlaping or duplicate.
  * @param string $attribute the attribute currently being validated
  * @param array $params the additional name-value pairs given in the rule
  */
  public function checkDuplicate($attribute, $params)
  {
    if (!$this->hasErrors()) {
      $already=self::find()
      ->where(['user_id'=>$this->user_id,'city_id'=>$this->city_id,'license_expiry'=>$this->license_expiry,'trashed'=>0])
      ->andFilterWhere(['!=','id',$this->id]);
      if($already->exists()){
        $this->addError($attribute, 'Record already exists.');
      }
    }
  }

  /**
  * @inheritdoc
  */
  public function attributeLabels()
  {
    return [
      'id' => Yii::t('app', 'ID'),
      'user_id' => Yii::t('app', 'Member'),
      'city_id' => Yii::t('app', 'City'),
      'license_image' => Yii::t('app', 'License Photo'),
      'license_start' => Yii::t('app', 'License Start'),
      'license_expiry' => Yii::t('app', 'License Expiry'),
    ];
  }

	/**
	* @inheritdoc
	*/
	public function behaviors()
	{
		return [
			'timestamp' => [
				'class' => TimestampBehavior::className(),
				'attributes' => [
					ActiveRecord::EVENT_BEFORE_INSERT => ['created_at','updated_at'],
					ActiveRecord::EVENT_BEFORE_UPDATE => 'updated_at',
				],
				'value' => function($event) {
					return date("Y-m-d H:i:s");
				},
			],
			'blameable' => [
				'class' => BlameableBehavior::className(),
				'createdByAttribute' => 'created_by',
				'updatedByAttribute' => 'updated_by',
			],
      'LoggableBehavior' => [
				'class' => ActivityLogBehaviorUser::className(),
			],
		];
	}

  /**
   * @return \yii\db\ActiveQuery
   */
  public function getMember()
  {
	   return $this->hasOne(User::className(), ['id' => 'user_id']);
  }

  /**
   * @return \yii\db\ActiveQuery
   */
  public function getCreatedByUser()
  {
	   return $this->hasOne(User::className(), ['id' => 'created_by']);
  }

  /**
   * @return string, name of user
   */
  public function getCreatedBy()
  {
    if($this->createdByUser!=null){
	   return $this->createdByUser->fullname;
    }
  }

  /**
   * @return \yii\db\ActiveQuery
   */
  public function getUpdatedByUser()
  {
	   return $this->hasOne(User::className(), ['id' => 'updated_by']);
  }

  /**
   * @return string, name of user
   */
  public function getUpdatedBy()
  {
    if($this->updatedByUser!=null){
      return $this->updatedByUser->fullname;
    }
  }

  /**
  * @inheritdoc
  */
  public function beforeValidate()
  {
    //Uploading Logo
    if(UploadedFile::getInstance($this, 'license_image')){
      $this->imageFile = UploadedFile::getInstance($this, 'license_image');
      // if no file was uploaded abort the upload
      if (!empty($this->imageFile)) {
        $pInfo=pathinfo($this->imageFile->name);
        $ext = $pInfo['extension'];
        if (in_array($ext,$this->allowedImageTypes)) {
          // Check to see if any PHP files are trying to be uploaded
          $content = file_get_contents($this->imageFile->tempName);
          if (preg_match('/\<\?php/i', $content)) {
            $this->addError('license_image', Yii::t('app', 'Invalid file provided!'));
            return false;
          }else{
            if (filesize($this->imageFile->tempName) <= $this->allowedImageSize) {
              // generate a unique file name
              $this->license_image = Yii::$app->fileHelperFunctions->generateName().".{$ext}";
            }else{
              $this->addError('license_image', Yii::t('app', 'File size is too big!'));
              return false;
            }
          }
        }else{
          $this->addError('license_image', Yii::t('app', 'Invalid file provided!'));
          return false;
        }
      }
    }
    if($this->license_image==null && $this->oldImage!=null){
      $this->license_image=$this->oldImage;
    }
    return parent::beforeValidate();
  }

  /**
  * @inheritdoc
  */
  public function afterSave($insert, $changedAttributes)
  {
    if ($this->imageFile!== null && $this->license_image!=null) {
      if($this->oldImage!=null && $this->license_image!=$this->oldImage && file_exists(Yii::$app->params['member_license_uploads_abs_path'].$this->oldImage)){
        unlink(Yii::$app->params['member_license_uploads_abs_path'].$this->oldImage);
      }
      $this->imageFile->saveAs(Yii::$app->params['member_license_uploads_abs_path'].$this->license_image);
    }
    parent::afterSave($insert, $changedAttributes);
  }

  /**
   * Mark record as deleted and hides fron list.
   * @return boolean
   */
	public function softDelete()
	{
		$connection = \Yii::$app->db;
		$connection->createCommand(
      "update ".self::tableName()." set trashed=:trashed,trashed_at=:trashed_at,trashed_by=:trashed_by where id=:id",
      [
        ':trashed'=>1,
        ':trashed_at'=>date("Y-m-d H:i:s"),
        ':trashed_by'=>Yii::$app->user->identity->id,
        ':id'=>$this->id,
      ]
    )
    ->execute();
    ActivityLog::add(ActivityLog::LOG_STATUS_SUCCESS, 'License record ('.$this->member->fullname.') trashed successfully');
		return true;
	}

  public function sendExpiryEmail()
  {
    $subject = Yii::$app->helperFunctions->getLicenseReminderSubject($this->city_id);

    $message = Yii::$app->mailer->compose(['html' => 'licenseExpiryReminder'.$this->city_id.'-html', 'text' => 'licenseExpiryReminder'.$this->city_id.'-text'], ['model' => $this]);
    $message->setFrom([Yii::$app->params['icareEmail'] => Yii::$app->params['siteName']]);
    $message->setTo($this->member->email);
    $message->setSubject($subject.' - ' . Yii::$app->params['siteName']);
    //Abu Dhabi
    if($this->city_id==735){
      $message->attach(Yii::$app->params['downloads_abs_Path'].'Guidelines for FTA Local License Renewal.pdf');
      $message->attach(Yii::$app->params['downloads_abs_Path'].'Guidelines on how to pay online for  FTA License Renewal.pdf');
    }
    //Dubai
    elseif($this->city_id==736){
      //
    }
    $message->send();
    return true;
  }
}

controllers/UserLicenseController.php
<?php

namespace app\controllers;

use Yii;
use app\models\User;
use app\models\UserLicense;
use app\models\UserLicenseSearch;
use app\components\helpers\DefController;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
* UserLicenseController implements the CRUD actions for User Note model.
*/
class UserLicenseController extends DefController
{
  /**
  * @inheritdoc
  */
  public function behaviors()
  {
    return [
      'verbs' => [
        'class' => VerbFilter::className(),
        'actions' => [
          'delete' => ['POST'],
        ],
      ],
    ];
  }

  /**
  * Creates a new UserLicense model.
  * @return mixed
  */
  public function actionCreate($user_id=null)
  {
    $this->checkSuperAdmin();
    if($user_id==null){
      throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
    $model = new UserLicense;
    $model->user_id=$user_id;

    if ($model->load(Yii::$app->request->post())) {
      if($model->save()){
        echo 'success';
        exit;
      }else{
        if($model->hasErrors()){
          foreach($model->getErrors() as $error){
            if(count($error)>0){
              foreach($error as $key=>$val){
                echo $val;
                die();
              }
            }
          }
        }
      }
    }
    return $this->renderAjax('_form', [
      'model' => $model,
    ]);
  }

  /**
  * Update a UserLicense model.
  * @return mixed
  */
  public function actionUpdate($id)
  {
    $this->checkSuperAdmin();
    $model = $this->findModel($id);
    $model->oldImage=$model->license_image;

    if ($model->load(Yii::$app->request->post())) {
      if($model->save()){
        echo 'success';
        exit;
      }else{
        if($model->hasErrors()){
          foreach($model->getErrors() as $error){
            if(count($error)>0){
              foreach($error as $key=>$val){
                echo $val;
                die();
              }
            }
          }
        }
      }
    }
    return $this->renderAjax('_form', [
      'model' => $model,
    ]);
  }

  /**
   * Deletes an existing model.
   * If deletion is successful, the browser will be redirected to the 'index' page.
   * @param integer $id
   * @return mixed
   * @throws NotFoundHttpException if the model cannot be found
   */
  public function actionDelete($id)
  {
    $this->checkLogin();
      $this->findModel($id)->softDelete();
      echo "success";
      exit;
  }

  /**
  * Finds the UserLicense model based on its primary key value.
  * If the model is not found, a 404 HTTP exception will be thrown.
  * @param integer $id
  * @return User the loaded model
  * @throws NotFoundHttpException if the model cannot be found
  */
  protected function findModel($id)
  {
    if (($model = UserLicense::findOne($id)) !== null) {
      return $model;
    }

    throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
  }
}

views/user-license/_form.php
<?php

use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\User */
/* @var $form yii\widgets\ActiveForm */

$this->registerJs('
$(".dtpicker").datepicker({
	format: "yyyy-mm-dd",
	todayHighlight: true,
}).on("changeDate", function(e){
	$(this).datepicker("hide");
});
');

$licenseImage=Yii::$app->fileHelperFunctions->getImagePath('user_license',$model['license_image'],'tiny');
?>
<?php $form = ActiveForm::begin(['id'=>'licenseForm','options'=>['enctype'=>'multipart/form-data']]); ?>
<?= $form->field($model, 'city_id')->dropDownList(Yii::$app->appHelperFunctions->cityListArr) ?>
<div class="row">
	<div class="col-sm-6">
		<?= $form->field($model, 'license_start')->textInput(['class'=>'form-control dtpicker','readonly'=>'readonly']) ?>
	</div>
	<div class="col-sm-6">
		<?= $form->field($model, 'license_expiry')->textInput(['class'=>'form-control dtpicker','readonly'=>'readonly']) ?>
	</div>
</div>
<?= $form->field($model, 'license_image',['template'=>'
{label}
<div class="input-group file-input">
<div class="input-group-prepend">
<span class="input-group-text"><img src="'.$licenseImage.'" /></span>
</div>
<div class="custom-file">
{input}
<label class="custom-file-label" for="fldImg">Choose file</label>
</div>
</div>
{error}{hint}
'])->fileInput(['id'=>'fldImg','class'=>'custom-file-input','accept'=>'image/*']) ?>
<div class="row">
	<div class="col-md-12">
		<?= Html::submitButton(Yii::t('app', 'Update'), ['class' => 'btn btn-primary']) ?>
		<?= Html::a('Cancel', 'javascript:;', ['class' => 'btn btn-default', 'data-dismiss'=>'modal']) ?>
	</div>
</div>
<?php ActiveForm::end(); ?>

views/user-license/_gridview.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use app\components\widgets\CustomGridView;

$createBtn=false;
$actionBtns="";
if(Yii::$app->controller->id=="user" && Yii::$app->controller->action->id=='update'){
	$actionBtns='{view}';
}

if(Yii::$app->menuHelperFunction->checkActionAllowed('update','user-license')){
  $actionBtns.='{update}';
}
if(Yii::$app->menuHelperFunction->checkActionAllowed('delete','user-license')){
  $actionBtns.='{delete}';
}
?>
<?= CustomGridView::widget([
  'dataProvider' => $dataProvider,
  'filterModel' => $searchModel,
  'createBtn' => $createBtn,
  'cardHeader' => false,
  'columns' => [
    ['class' => 'yii\grid\SerialColumn','headerOptions'=>['class'=>'noprint','style'=>'width:15px;']],
    ['format' => ['image',['width'=>'40','height'=>'40']],'label'=>'Photo','attribute'=>'license_image','value'=>function($model){
      return Yii::$app->fileHelperFunctions->getImagePath('user_license',$model['license_image'],'small');
    },'headerOptions'=>['class'=>'noprint fxd1'],'contentOptions'=>['class'=>'fxd1']],
    ['attribute'=>'city_name','label'=>'City'],
    ['format'=>'date','attribute'=>'license_start','label'=>'Start'],
    ['format'=>'date','attribute'=>'license_expiry','label'=>'Expiry'],
    [
      'class' => 'yii\grid\ActionColumn',
      'header'=>'',
      'headerOptions'=>['class'=>'noprint','style'=>'width:50px;'],
      'contentOptions'=>['class'=>'noprint actions'],
      'template' => '
        <div class="btn-group flex-wrap">
          <button type="button" class="mb-1 mt-1 mr-1 btn btn-xs btn-default dropdown-toggle" data-toggle="dropdown">
            <span class="caret"></span>
          </button>
          <div class="dropdown-menu" role="menu">
            '.$actionBtns.'
          </div>
        </div>',
      'buttons' => [
          'view' => function ($url, $model) {
            return Html::a('<i class="fas fa-table"></i> '.Yii::t('app', 'View'), 'javascript:;', [
              'title' => Yii::t('app', 'View'),
              'class'=>'dropdown-item text-1 btn-view',
              'data-pjax'=>"0",
              'data-photo'=>Yii::$app->fileHelperFunctions->getImagePath('user_license',$model['license_image'],'medium'),
              'data-city'=>$model['city_name'],
              'data-start_date'=>Yii::$app->formatter->asDate($model['license_start']),
              'data-end_date'=>Yii::$app->formatter->asDate($model['license_expiry']),
            ]);
          },
          'update' => function ($url, $model) {

						if(Yii::$app->controller->id=="user" && Yii::$app->controller->action->id=='update'){
							$htmlModal="general-modal";
						}else{
							$htmlModal="general-modal-secondary";
						}
            $memberName=Yii::$app->helperFunctions->getMemberFullName($model['username'],$model['firstname'],$model['lastname']);
            return Html::a('<i class="fas fa-edit"></i> '.Yii::t('app', 'Edit'), 'javascript:;', [
              'title' => Yii::t('app', 'Edit'),
              'class'=>'dropdown-item text-1 nosd load-modal',
              'data-url'=>Url::to(['user-license/update','id'=>$model['id']]),
              'data-heading'=>''.$memberName.' - Update License',
              'data-mid'=>$htmlModal,
              'data-pjax'=>"0",
            ]);
          },
          'delete' => function ($url, $model) {
            $memberName=Yii::$app->helperFunctions->getMemberFullName($model['username'],$model['firstname'],$model['lastname']);
            return Html::a('<i class="fas fa-trash"></i> '.Yii::t('app', 'Delete'), 'javascript:;', [
              'title' => Yii::t('app', 'Delete'),
              'class'=>'dropdown-item text-1 nosd del-lic',
              'data-id'=>$model['id'],
              'data-username'=>''.$memberName.'',
              'data-pjax'=>"0",
            ]);
          },
      ],
    ],
  ],
]);?>

views/user-license/index.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use app\components\widgets\CustomPjax;

/* @var $this yii\web\View */
/* @var $searchModel app\models\UserLicenseSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$createBtn=false;
if(Yii::$app->menuHelperFunction->checkActionAllowed('create','user-license')){
  $createBtn=true;
}
?>
<style>
.filters{display: none;}
</style>
<div class="user-license-index">
  <?php if($createBtn==true){?>
  <div class="row">
    <div class="col-sm-12 text-right">
      <a href="javascript:;" class="btn btn-success btn-xs load-modal" data-url="<?= Url::to(['user-license/create','user_id'=>$model->id])?>" data-heading=" <?= $model->fullname?> - Add License"><i class="fa fa-plus"></i></a>
    </div>
  </div>
  <?php }?>
  <?php CustomPjax::begin(['id'=>'grid-container']); ?>
  <?= $this->render('_gridview',['searchModel'=>$searchModel,'dataProvider'=>$dataProvider,'model'=>$model])?>
  <?php CustomPjax::end(); ?>
</div>

<script>
function showDetail(_t){
  html = '';
  html+= '<div class="row">';
  html+= '  <div class="col-xs-12 col-sm-12">';
  html+= '<table class="view-detail table table-striped table-bordered">';
  if(_t.data("photo")!='' && _t.data("photo")!=undefined){
  html+= '  <tr>';
  html+= '    <th><?= Yii::t('app','Photo:')?></th>';
  html+= '    <td><img src="'+_t.data("photo")+'" alt="" /></td>';
  html+= '  </tr>';
  }
  html+= '  <tr>';
  html+= '    <th width="150"><?= Yii::t('app','City:')?></th>';
  html+= '    <td>'+_t.data("city")+'</td>';
  html+= '  </tr>';
  if(_t.data("start_date")!='' && _t.data("start_date")!=undefined){
  html+= '  <tr>';
  html+= '    <th><?= Yii::t('app','Start:')?></th>';
  html+= '    <td>'+_t.data("start_date")+'</td>';
  html+= '  </tr>';
  }
  if(_t.data("end_date")!='' && _t.data("end_date")!=undefined){
  html+= '  <tr>';
  html+= '    <th><?= Yii::t('app','Expiry:')?></th>';
  html+= '    <td>'+_t.data("end_date")+'</td>';
  html+= '  </tr>';
  }
  html+= '</table>';

  html+= '  </div>';
  html+= '</div>';
  viewPopUpModal("<?= $model->fullname.' - '.Yii::t('app','License Detail')?>",html)
}
</script>
<?= $this->render('/user-license/js/user_license_scritps')?>