controllers/UserController.php
<?php

namespace app\controllers;

use Yii;
use app\models\User;
use app\models\UserSearch;
use app\models\UserNoteSearch;
use app\models\SecurityDepositForm;
use app\models\UserFeedback;
use app\models\BookingSearch;
use app\models\RequestsSearch;
use app\models\UserLicenseSearch;
use app\models\Contract;
use app\models\Newsletter;
use app\models\UserPasswordResetForm;
use app\components\helpers\DefController;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\ArrayHelper;

/**
* UserController implements the CRUD actions for User model.
*/
class UserController extends DefController
{
  /**
  * @inheritdoc
  */
  public function behaviors()
  {
    return [
      'verbs' => [
        'class' => VerbFilter::className(),
        'actions' => [
          'delete' => ['POST'],
        ],
      ],
    ];
  }

  /**
  * Lists all User models.
  * @return mixed
  */
  public function actionIndex()
  {
    $this->checkAdmin();
    $searchModel = new UserSearch();
    $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

    $mailModel = new Newsletter;
    $mailModel->keyword = $searchModel->keyword;
    $mailModel->credit_balance = $searchModel->credit_balance;
    $mailModel->is_licensed = $searchModel->is_licensed;
    $mailModel->package_idz = $searchModel->package_name!=null ? implode(",",$searchModel->package_name) : null;
    //$mailModel->city_idz = $searchModel->city_name!=null ? implode(",",$searchModel->city_name) : null;
    $mailModel->status = $searchModel->status;
    $mailModel->tasks = $searchModel->tasks;
    $mailModel->expiry_month = $searchModel->expiry_month;
    if ($mailModel->load(Yii::$app->request->post())) {
      if($mailModel->save()){
        Yii::$app->getSession()->setFlash('success', Yii::t('app','Mail qeued successfully'));
        return $this->redirect(Yii::$app->request->referrer ?: ['index']);
      }else{
        if($mailModel->hasErrors()){
          foreach($mailModel->getErrors() as $error){
            if(count($error)>0){
              foreach($error as $key=>$val){
                Yii::$app->getSession()->addFlash('error', $val);
              }
            }
          }
        }
      }
    }

    return $this->render('index', [
      'searchModel' => $searchModel,
      'dataProvider' => $dataProvider,
      'mailModel' => $mailModel,
    ]);
  }

  /**
  * Creates a new User model.
  * If creation is successful, the browser will be redirected to the 'view' page.
  * @return mixed
  */
  public function actionCreate()
  {
    $this->checkSuperAdmin();
    $model = new User();
    $model->user_type=0;
    $model->permission_group_id=2;
    $model->status=20;
    $model->scenario = 'new';

    if ($model->load(Yii::$app->request->post())) {
      if($model->save()){
        //$this->updateContract($model);
        Yii::$app->getSession()->setFlash('success', Yii::t('app','Information saved successfully'));
        return $this->redirect(['index']);
      }else{
        if($model->hasErrors()){
          foreach($model->getErrors() as $error){
            if(count($error)>0){
              foreach($error as $key=>$val){
                Yii::$app->getSession()->addFlash('error', $val);
              }
            }
          }
        }
      }
    }


    return $this->render('create', [
      'model' => $model,
    ]);
  }

  /**
  * Updates an existing User model.
  * @param integer $id
  * @return mixed
  * @throws NotFoundHttpException if the model cannot be found
  */
  public function actionUpdate($id)
  {
    $this->checkSuperAdmin();
    $model = $this->findModel($id);
    $oldEmail=$model->email;
    $model->scenario = 'update';
    $model->oldfile=$model->image;
    //$model->oldlicensefile=$model->license_image;

    if ($model->load(Yii::$app->request->post())) {
      if($model->save()){
        if($oldEmail!=$model->email){
          $model->sendEmailChangedAlert();
        }
        Yii::$app->getSession()->addFlash('success', Yii::t('app','Information saved successfully'));
        return $this->redirect(['index']);
      }else{
        if($model->hasErrors()){
          foreach($model->getErrors() as $error){
            if(count($error)>0){
              foreach($error as $key=>$val){
                Yii::$app->getSession()->addFlash('error', $val);
              }
            }
          }
        }
      }
    }

    $licenseSearchModel = new UserLicenseSearch();
    $licenseSearchModel->user_id=$id;
    $licenseDataProvider = $licenseSearchModel->search(Yii::$app->request->queryParams);

    $searchModel = new UserNoteSearch();
    $searchModel->user_id=$id;
    $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
    $dataProvider->pagination->pageSize=5;

    return $this->render('update', [
      'searchModel' => $searchModel,
      'dataProvider' => $dataProvider,

      'licenseSearchModel' => $licenseSearchModel,
      'licenseDataProvider' => $licenseDataProvider,
      'model' => $model,
    ]);
  }

  public function actionResetUserPassword($id)
  {
    $this->checkSuperAdmin();
    $modelUser=$this->findModel($id);
    $model=new UserPasswordResetForm;
    $model->user_id=$modelUser->id;
    if ($model->load(Yii::$app->request->post())) {
      $msg=[];
      if($model->save()){
        $msg['success']=['heading'=>Yii::t('app','Success'),'msg'=>Yii::t('app','Password reset successfully')];
        echo json_encode($msg);
        exit;
      }else{
        if($model->hasErrors()){
          foreach($model->getErrors() as $error){
            if(count($error)>0){
              foreach($error as $key=>$val){
                $msg['error']=['heading'=>Yii::t('app','Error'),'msg'=>$val];
                echo json_encode($msg);
                exit;
              }
            }
          }
        }
      }

    }

    return $this->renderAjax('reset_user_password', [
      'model' => $model,
    ]);
  }

  /**
  * Mark Dead Membership
  * @param integer $id
  * @return mixed
  */
  public function actionMarkDead($id)
  {
    $this->checkSuperAdmin();
    $model=$this->findModel($id);

    $connection = \Yii::$app->db;
    $connection->createCommand("update ".User::tableName()." set status=:user_status where id=:user_id",[':user_status'=>5,':user_id'=>$model->id])->execute();
    echo 'dead';
    exit;
  }

  /**
  * Feedback from user
  * @param integer $id
  * @return mixed
  */
  public function actionSecurityDeposit($id)
  {
    $this->checkSuperAdmin();
    $model = new SecurityDepositForm();
    $model->user_id=$id;
    $model->amount=$model->user->profileInfo->security_deposit;
    $model->deposit_type=$model->user->profileInfo->deposit_type;
    if ($model->load(Yii::$app->request->post())) {
      if($model->send()){
        echo 'success';
      }else{
        $n=1;
        foreach($model->getErrors() as $error){
          foreach($error as $key=>$val){
            echo $val.($n>1 ? ', ' : '');
          }
          $n++;
        }
      }
      exit;
    }
    return $this->renderAjax('security_deposit_form', [
      'model' => $model,
    ]);
  }

  /**
  * Lists all Members Booking models.
  * @return mixed
  */
  public function actionBookings($id,$contract_id=null,$listType='future')
  {
    $this->checkSuperAdmin();
    $model = $this->findModel($id);

    if($contract_id==null){
      $contract_id=$model->active_contract_id;
    }

    $contract=Contract::findOne($contract_id);

    $searchModel = new BookingSearch();
    $searchModel->contract_id=$contract_id;
    $searchModel->user_id=$id;
    $searchModel->listType=$listType;
    if($contract!=null){
      $searchModel->booking_date=$contract->start_date.' - '.$contract->end_date;
    }
    $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

    return $this->render('bookings', [
      'model' => $model,
      'contract' => $contract,
      'searchModel' => $searchModel,
      'dataProvider' => $dataProvider,
    ]);
  }

  /**
  * Lists all Members Booking models.
  * @return mixed
  */
  public function actionRequests($id,$listType='future')
  {
    $this->checkSuperAdmin();
    $model = $this->findModel($id);
    $searchModel = new RequestsSearch();
    $searchModel->user_id=$id;
    $searchModel->listType=$listType;
    $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

    return $this->render('requests', [
      'model' => $model,
      'searchModel' => $searchModel,
      'dataProvider' => $dataProvider,
    ]);
  }

  /**
  * Creates a new model.
  */
  protected function newModel()
  {
    $model = new User;
    return $model;
  }

  /**
  * Lists all User models.
  * @return mixed
  */
  public function actionSearch($id=null)
  {
    $this->checkSuperAdmin();
    $model = new User;
    if($id!=null){
      $model = $this->findModel($id);
    }

    return $this->render('search', [
      'model' => $model,
    ]);
  }

  /**
  * Lists all User models.
  * @return mixed
  */
  public function actionUpdateInfo($id=null)
  {
    $this->checkSuperAdmin();
    $searchModel = new UserSearch();
    $searchModel->user_type=0;
    $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

    return $this->render('update_info', [
      'searchModel' => $searchModel,
      'dataProvider' => $dataProvider,
    ]);
  }

  public function actionUpdateMemberInfo($id)
  {
    $this->checkSuperAdmin();
    $model = $this->findModel($id);
    $model->oldfile=$model->image;
    $model->joining_date=$model->profileInfo->joining_date;
    $model->membership_number=$model->profileInfo->membership_number;
    //$model->oldlicensefile=$model->license_image;
    //$model->license_expiry=$model->profileInfo->license_expiry;
    //$model->license_image=$model->profileInfo->license_image;
    if ($model->load(Yii::$app->request->post())) {
      if($model->save()){
        echo 'success';
        exit;
      }else{
        if($model->hasErrors()){

views/user/bookings.php
<?php
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;
use app\components\widgets\CustomTabbedGridView;
use app\components\widgets\CustomPjax;
use app\widgets\UsersTabStart;
use app\assets\MemberBookingListAssets;
MemberBookingListAssets::register($this);

/* @var $this yii\web\View */
/* @var $searchModel app\models\BookingSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title =$model->fullname.' - ';

if($searchModel->listType=='future'){
  $this->title .= Yii::t('app', 'Active Bookings');
}elseif($searchModel->listType=='history'){
  $this->title .= Yii::t('app', 'Booking History');
}elseif($searchModel->listType=='deleted'){
  $this->title .= Yii::t('app', 'Deleted Bookings');
}

$this->params['breadcrumbs'][] = ['label' => Yii::t('app','Members'), 'url' => ['user/index']];
$this->params['breadcrumbs'][] = $this->title;

$actionBtns='';
$createBtnLink=[];
$createBtn=false;
if($searchModel->listType=='future' && Yii::$app->menuHelperFunction->checkActionAllowed('new-user-booking','booking')){
  $createBtn=true;
  $createBtnLink=['booking/new-user-booking','user_id'=>$model->id];
}

if($searchModel->city_id!=null){
  $marinaList=Yii::$app->appHelperFunctions->getActiveCityMarinaListArr($searchModel->city_id);
}else{
  $marinaList=Yii::$app->appHelperFunctions->activeMarinaListArr;
}

$boatsList=Yii::$app->appHelperFunctions->getActiveBoatsListArr($searchModel->city_id,$searchModel->port_id);

$columns[]=['class' => 'yii\grid\SerialColumn'];
$columns[]=['format'=>'html','attribute'=>'member_name','label'=>'Member','value' => function ($model){
  return $model->member->fullname.'<br /><span class="badge badge-info">'.Yii::$app->formatter->asDateTime($model['created_at']).'</span>'.($model['trashed']==1 ? '<br /><span class="badge badge-danger">'.Yii::$app->formatter->asDateTime($model['trashed_at']).'</span>' : '');
}];
$columns[]=['format'=>'html','attribute'=>'city_id','label'=>'City','value' => function ($model){return ($model->city!=null ? $model->city->name : 'Not set');},'filter'=>Yii::$app->appHelperFunctions->activeCityListArr];
$columns[]=['format'=>'html','attribute'=>'port_id','label'=>'Marina','value' => function ($model){return ($model->marina!=null ? $model->marina->name : 'Not set');},'filter'=>$marinaList];
$columns[]=['format'=>'html','attribute'=>'boat_id','label'=>'Boat','value' => function ($model){return ($model->boat!=null ? $model->boat->name : 'Not set');},'filter'=>$boatsList];
$columns[]=['format'=>'date','attribute'=>'booking_date','filterInputOptions'=>['class'=>'form-control dtpicker','autocomplete'=>'off']];
$columns[]=['format'=>'html','attribute'=>'booking_time_slot','label'=>'Time','value' => function ($model){return $model->timeZone->name.($model->booking_time_slot==3 ? ' <span style="color:red;">Marina Stay in</span>' : '');},'filter'=>Yii::$app->appHelperFunctions->timeSlotListArr];
if(Yii::$app->user->identity->user_type!=0){
  $columns[]=['format'=>'raw','attribute'=>'booking_type','label'=>'Remarks','value'=>function($model){return $model->remarks;},'filter'=>Yii::$app->helperFunctions->adminBookingTypes];
}
$columns[]=['format'=>'raw','label'=>'Addons','value' => function ($model){return $model->addonsMenu;},'contentOptions'=>['class'=>'nosd']];
if($searchModel->listType!='deleted'){
$columns[] = ['format'=>'html','label'=>'Status','attribute'=>'status','value'=>function($model){return '<span class="badge badge-'.($model->status==1 ? 'success' : 'dark').'">'.Yii::$app->helperFunctions->bookingStatus[$model->status].'</span>';},'filter'=>false];
}
$columns[]=[
  'class' => 'yii\grid\ActionColumn',
  'header'=>'Actions',
  'headerOptions'=>['class'=>'noprint','style'=>'width:75px;'],
  'contentOptions'=>['class'=>'noprint'],
  'template' => '{booking-activity} {delete}',
  'buttons' => [
    'booking-activity' => function ($url, $model) use ($searchModel){
      if($searchModel->listType=='history'){
      //if(Yii::$app->menuHelperFunction->checkActionAllowed('activity-detail','booking')){
        return Html::a('<i class="fa fa-list"></i> View Activity', 'javascript:;', [
          'title' => Yii::t('app', 'View Activity'),
          'class'=>'mb-xs mt-xs mr-xs btn btn-xs btn-info load-modal',
          'data-heading'=>'Booking Activity',
          'data-url'=>Url::to(['booking/activity-detail','id'=>$model->id]),
        ]);
      //}
      }
    },
    'delete' => function ($url, $model) use ($searchModel){
      if($searchModel->listType=='future'){
        if(date("Y-m-d",strtotime($model->booking_date))>=date("Y-m-d")){
          return Html::a('<i class="fa fa-trash"></i> Delete', 'javascript:;', [
            'title' => Yii::t('app', 'Delete'),
            'class'=>'mb-xs mt-xs mr-xs btn btn-xs btn-danger',
            'onclick'=>'javascript:deleteBooking('.$model->id.');',
            'data-id'=>$model->id,
            'data-method'=>"post",
          ]);
        }
      }
    },
  ],
];
?>
<style>
.dropdown-item.text-1.highlightIt{background-color:#e6e6e6;color:#000;font-weight:bold;}
</style>
<div class="city-index">
  <?= UsersTabStart::header($model,$searchModel)?>
  <?php CustomPjax::begin(['id'=>'grid-container']); ?>
  <div class="btn-group flex-wrap">
		<button type="button" class="mb-1 mt-1 mr-1 btn btn-default dropdown-toggle" data-toggle="dropdown">
      <?= $contract->package->name?> (<small><strong>From:</strong> <?= Yii::$app->formatter->asDate($contract->start_date);?> | <strong>To:</strong> <?= Yii::$app->formatter->asDate($contract->end_date);?></small>)
      <span class="caret"></span>
    </button>
		<div class="dropdown-menu" role="menu">
      <?php
      $memberContracts=$model->lastFiveContracts;
      if($memberContracts!=null){
        foreach($memberContracts as $memberContract){
          $contractTitle=$memberContract['package_name'].' (<small><strong>From:</strong> '.Yii::$app->formatter->asDate($memberContract['start_date']).' | <strong>To:</strong> '.Yii::$app->formatter->asDate($memberContract['end_date']).'</small>)';
          echo Html::a($contractTitle,['user/bookings','id'=>$model->id,'contract_id'=>$memberContract['id'],'listType'=>$searchModel->listType],['class'=>'dropdown-item text-1'.($searchModel->contract_id==$memberContract['id'] ? ' highlightIt' : '')]);
        }
      }
      ?>
		</div>
	</div>
  <?php if($searchModel->listType=='bookingstats'){?>
    <?= $this->render('booking_stats',['user'=>$model,'searchModel'=>$searchModel,'contract'=>$contract])?>
  <?php }else{?>
  <?= CustomTabbedGridView::widget([
    'dataProvider' => $dataProvider,
    'filterModel' => $searchModel,
    'createBtn' => $createBtn,
    'createBtnLink' => $createBtnLink,
    'createInPopUp' => true,
    'popUpHeading' => 'New Member Booking',
    'rowOptions' => function ($model, $index, $widget, $grid){
      return ['class'=>'item-row','data-city_id'=>$model->city_id, 'data-marina_id'=>$model->port_id];
    },
    'columns' => $columns,
  ]);?>
  <?php }?>
  <?php CustomPjax::end(); ?>
  <?= UsersTabStart::footer()?>
</div>
<?= $this->render('/booking/js/list_script')?>
<?= $this->render('/booking/js/update_comments_scripts')?>
<?= $this->render('/site/admin/js/scripts')?>

views/user/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = Yii::t('app', 'New Member');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app','Members'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-create">
    <?= $this->render('_form', [
        'model' => $model,
        'licenseSearchModel' => null,
        'licenseDataProvider' => null,
    ]) ?>
</div>

views/user/member_request_selection.php
<?php
echo $this->render('/request/selection',['user'=>$model]);
?>

views/user/membership_card.php
<?php
$avatarImg=Yii::$app->fileHelperFunctions->getImagePath('user',$model->image,'medium');
?>
<section class="body-sign membership-card" style="padding: 0 5px;">
  <div class="panel card-sign">
    <div class="card-title-sign mt-3 text-center">
      <h2 class="title text-uppercase font-weight-bold m-0">
        <img src="images/logo.png" alt="The Captains Club" height="80">
      </h2>
    </div>
    <div class="card-body">
      <div class="bg-memcard clearfix">
        <img src="<?= $avatarImg?>" class="photo pull-left" alt="<?= $model->firstname?>" />
        <div class="mem-info pull-left">
          <strong>Name: </strong> <?= $model->firstname.' '.$model->lastname?><br />
          <strong>Membership#: </strong> <?= $model->profileInfo->membership_number;?><br />
          <strong>Category: </strong> <?= $model->activeContract->package_name?><br />
          <strong>Joining Date: </strong> <?= $model->profileInfo->joining_date!=null ? Yii::$app->formatter->asDate($model->profileInfo->joining_date,"php: M d, Y") : ''?><br />
        </div>
    </div>
  </div>
</section>

views/user/requests.php
<?php
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;
use app\components\widgets\CustomTabbedGridView;
use app\components\widgets\CustomPjax;
use app\widgets\UsersTabStart;
use app\models\User;
use app\models\LogUserRequestToBoatAssign;
use app\assets\UserRequestAssets;
UserRequestAssets::register($this);

/* @var $this yii\web\View */
/* @var $searchModel app\models\BookingSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title =$model->fullname.' - ';

if($searchModel->listType=='future'){
  $this->title .= Yii::t('app', 'Active Requests');
}elseif($searchModel->listType=='history'){
  $this->title .= Yii::t('app', 'Requests History');
}

$this->params['breadcrumbs'][] = ['label' => Yii::t('app','Members'), 'url' => ['user/index']];
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="user-requests-index">
  <?= UsersTabStart::header($model,$searchModel)?>
  <?= $this->render('/user-requests/_gridview',[
    'searchModel'=>$searchModel,
    'dataProvider'=>$dataProvider,
  ])?>
  <?= UsersTabStart::footer()?>
</div>
<?= $this->render('/request/js/boat_booking_scripts')?>

views/user/update_info.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use yii\helpers\ArrayHelper;
use app\components\widgets\CustomGridView;
use app\components\widgets\CustomPjax;
use app\models\User;
use app\models\UserLicense;
use app\models\Package;
use app\models\Cities;
use yii\widgets\ActiveForm;
use app\assets\AppDatePickerAsset;
AppDatePickerAsset::register($this);

$this->title = Yii::t('app', 'Members');
$this->params['breadcrumbs'][] = $this->title;

$cities=Yii::$app->appHelperFunctions->activeCityList;

$gridBtnsArr='';
if(Yii::$app->menuHelperFunction->checkActionAllowed('update-info')){
	$gridBtnsArr.=' {update-info}';
}

$this->registerJs('
initScripts();
$(document).on("pjax:success", function() {
	initScripts();
});
$(document).delegate(".btn-load-form", "click", function() {
	id=$(this).data("id");
	username=$(this).data("username");
	$.ajax({
		url: "'.Url::to(['user/update-member-info','id'=>'']).'"+id,
		dataType: "html",
		success: function(data) {
			$("#general-modal").find("h5.modal-title").html("Update Info - "+username);
			$("#general-modal").find(".modalContent").html(data);
			$("#general-modal").modal();
			$(".dtpicker").datepicker({
				format: "yyyy-mm-dd",
				todayHighlight: true,
			}).on("changeDate", function(e){
				$(this).datepicker("hide");
			});
		},
		error: bbAlert
	});
});
$("body").on("beforeSubmit", "form#basicInfoFrm", function () {
	_targetContainer=$("#basicInfoFrm")
	App.blockUI({
		message: "'.Yii::t('app','Please wait...').'",
		target: _targetContainer,
		overlayColor: "none",
		cenrerY: true,
		boxed: true
	});

	 var form = $(this);
	 // return false if form still have some validation errors
	 if (form.find(".has-error").length) {
			return false;
	 }
	 var formData = new FormData(form[0]);
	 // submit form
	 $.ajax({
			url: form.attr("action"),
			type: "post",
			data: formData,
			success: function (response) {
				if(response=="success"){
					swal({title: "'.Yii::t('app','Saved').'", html: "'.Yii::t('app','Information updated successfully').'", type: "success"});
					window.closeModal();
				}else{
					swal({title: "'.Yii::t('app','Error').'", html: response, type: "error"});
				}
				App.unblockUI($(_targetContainer));
				$.pjax.reload({container: "#grid-container", timeout: 2000});
			},
	    cache: false,
	    contentType: false,
	    processData: false
	 });
	 return false;
});
');
?>
<?php CustomPjax::begin(['id'=>'grid-container']); ?>
<?= CustomGridView::widget([
'dataProvider' => $dataProvider,
'filterModel' => $searchModel,
'columns' => [
	['class' => 'yii\grid\SerialColumn'],
	['format'=>'html','attribute'=>'image','value'=>function($model){
		return Html::img(Yii::$app->fileHelperFunctions->getImagePath('user',$model['image'],'small'),['width'=>100,'height'=>100]);
	}],
	'username',
	'firstname',
	'lastname',
	['format'=>'raw','attribute'=>'status','label'=>Yii::t('app','Status'),'value'=>function($model){
		return Yii::$app->helperFunctions->getUserStatus($model['id'],$model['status'],$model);
	},'headerOptions'=>['class'=>'noprint fxd2'],'contentOptions'=>['class'=>'fxd2'],'filter'=>Yii::$app->helperFunctions->arrUserStatus],
	['format'=>'raw','label'=>'License','value'=>function($model) use ($cities){
		$html='';
		foreach($cities as $city){
			$licenseRow=UserLicense::find()->where(['user_id'=>$model['id'],'city_id'=>$city['id']])->asArray()->orderBy(['license_expiry'=>SORT_DESC])->one();
			if($licenseRow!=null){
				$licImage=Yii::$app->fileHelperFunctions->getImagePath('user_license',$licenseRow['license_image'],'small');
				if($licImage=="images/default/default.png"){
					$imgCode='<img src="'.$licImage.'" width="20" height="20" />';
				}else{
					$imgCode='<a><img src="'.$licImage.'" width="20" height="20" /></a>';
				}

				$html.='<table class="table table-responsive-lg table-sm table-striped table-hover mb-0">';
				$html.='	<tr>';
				$html.='		<td>'.$imgCode.'</td>';
				$html.='		<td>'.$city['name'].'</td>';
				$html.='		<td>'.Yii::$app->formatter->asDate($licenseRow['license_start']).' to '.Yii::$app->formatter->asDate($licenseRow['license_expiry']).'</td>';
				$html.='	</tr>';
				$html.='</table>';
			}
		}
		return $html;
	}],
	[
		'class' => 'yii\grid\ActionColumn',
		'header'=>'Actions',
		'template' => $gridBtnsArr,
		'buttons' => [
			'update-info' => function ($url, $model) {
				return Html::a('<i class="glyphicon glyphicon-pencil"></i> Update', 'javascript:;', [
					'title' => Yii::t('app', 'Update Member'),
					'data-id'=>$model['id'],
					'data-username'=>$model['username'],
					'class'=>'mb-xs mt-xs mr-xs btn btn-xs btn-success btn-load-form',
				]);
			},
			'license-info' => function ($url, $model) {
				return Html::a('<i class="glyphicon glyphicon-pencil"></i> License', 'javascript:;', [
					'title' => Yii::t('app', 'Add / Update License'),
					'class'=>'mb-xs mt-xs mr-xs btn btn-xs btn-info btn-load-form',
				]);
			},
		],
	],
],
'layout'=>"{items}<div>{summary}</div><div>{pager}</div>",
]); ?>
<?php CustomPjax::end(); ?>
<script>
function initScripts()
{
	$(".dtpicker").datepicker({
		format: "yyyy-mm-dd",
		todayHighlight: true,
	}).on("changeDate", function(e){
		$(this).datepicker("hide");
	});
}
</script>
<?= $this->render('/user-license/js/user_license_scritps')?>