models/UserAccounts.php
<?php

namespace app\models;

use Yii;
use yii\db\ActiveRecord;
use yii\behaviors\TimestampBehavior;
use yii\behaviors\BlameableBehavior;
use app\components\behaviors\ActivityLogBehaviorUser;

/**
* This is the model class for table "{{%user_accounts}}".
*
* @property integer $id
* @property integer $user_id
* @property integer $order_id
* @property string $trans_type
* @property string $descp
* @property integer $account_id
* @property integer $amount
* @property integer $profit
* @property integer $booking_id
*/
class UserAccounts extends ActiveRecord
{
  /**
  * @inheritdoc
  */
  public static function tableName()
  {
    return '{{%user_accounts}}';
  }

  /**
  * @inheritdoc
  */
  public function rules()
  {
    return [
      [['user_id','trans_type','descp','account_id','amount'], 'required'],
      [['trans_type','descp'], 'string'],
      [['user_id','booking_id', 'created_by', 'updated_by'], 'integer'],
      [['amount'], 'number'],
      [['created_at', 'updated_at'], 'safe'],
    ];
  }

  /**
  * @inheritdoc
  */
  public function attributeLabels()
  {
    return [
      'id' => Yii::t('app', 'ID'),
      'user_id' => Yii::t('app', 'User'),
      'trans_type' => Yii::t('app', 'Type'),
      'descp' => Yii::t('app', 'Detail'),
      'amount' => Yii::t('app', 'Amount'),
      'booking_id' => Yii::t('app', 'Booking'),
      'created_at' => Yii::t('app', 'Date & Time'),
    ];
  }

	/**
	* @inheritdoc
	*/
	public function behaviors()
	{
		return [
			'timestamp' => [
				'class' => TimestampBehavior::className(),
				'attributes' => [
					ActiveRecord::EVENT_BEFORE_INSERT => ['created_at','updated_at'],
					ActiveRecord::EVENT_BEFORE_UPDATE => 'updated_at',
				],
				'value' => function($event) {
					return date("Y-m-d H:i:s");
				},
			],
			'blameable' => [
				'class' => BlameableBehavior::className(),
				'createdByAttribute' => 'created_by',
				'updatedByAttribute' => 'updated_by',
			],
      'LoggableBehavior' => [
				'class' => ActivityLogBehaviorUser::className(),
			],
		];
	}

  /**
   * @return \yii\db\ActiveQuery
   */
  public function getCreatedByUser()
  {
	   return $this->hasOne(User::className(), ['id' => 'created_by']);
  }

  /**
   * @return string, name of user
   */
  public function getCreatedBy()
  {
    if($this->createdByUser!=null){
	   return $this->createdByUser->fullname;
    }
  }

  /**
   * @return \yii\db\ActiveQuery
   */
  public function getUpdatedByUser()
  {
	   return $this->hasOne(User::className(), ['id' => 'updated_by']);
  }

  /**
   * @return string, name of user
   */
  public function getUpdatedBy()
  {
    if($this->updatedByUser!=null){
      return $this->updatedByUser->fullname;
    }
  }

  /**
   * @return \yii\db\ActiveQuery
   */
  public function getMember()
  {
      return $this->hasOne(User::className(), ['id' => 'user_id']);
  }

  /**
   * @return \yii\db\ActiveQuery
   */
  public function getOrder()
  {
      return $this->hasOne(Order::className(), ['id' => 'order_id']);
  }

  /**
   * @return \yii\db\ActiveQuery
   */
  public function getBooking()
  {
      return $this->hasOne(Booking::className(), ['id' => 'booking_id']);
  }

  /**
   * @inheritdoc
   */
	public function afterSave($insert, $changedAttributes)
	{
    $amountsToPay = UserAccounts::find()->where(['trans_type'=>'dr','user_id'=>$this->user_id])->sum('amount');
    $ammountsPaid = UserAccounts::find()->where(['trans_type'=>'cr','user_id'=>$this->user_id])->sum('amount');
    $total = $ammountsPaid-$amountsToPay;
    $connection = \Yii::$app->db;
    $connection->createCommand(
      "update ".UserProfileInfo::tableName()." set credit_balance=:credit_balance where user_id=:id",
      [':credit_balance'=>$total,':id'=>$this->user_id]
    )
    ->execute();
    parent::afterSave($insert, $changedAttributes);
  }
}

controllers/UserAccountController.php
<?php

namespace app\controllers;

use Yii;
use app\models\User;
use app\models\AddUserCredit;
use app\models\ChargeUserCredit;
use app\models\AddSecurityDeposit;
use app\models\DeductSecurityDeposit;
use app\models\UserPaymentSearch;
use app\models\UserAccountsSearch;
use app\models\UserSecurityDepositSearch;
use app\components\helpers\DefController;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
* UserAccountController implements the CRUD actions for User Payments.
*/
class UserAccountController extends DefController
{
  /**
  * @inheritdoc
  */
  public function behaviors()
  {
    return [
      'verbs' => [
        'class' => VerbFilter::className(),
        'actions' => [
          'add-credit' => ['POST'],
          'charge-credit' => ['POST'],
        ],
      ],
    ];
  }

  /**
  * Lists Fuel Credit Log for User models.
  * @return mixed
  */
  public function actionCreditLog($id)
  {
    $this->checkSuperAdmin();
    $model=$this->findModel($id);
    $searchModel = new UserPaymentSearch();
    $searchModel->user_id=$id;
    $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

    return $this->render('old_credit_history', [
      'model' => $model,
      'searchModel' => $searchModel,
      'dataProvider' => $dataProvider,
    ]);
  }

  /**
  * Lists Fuel Credit Log for User models.
  * @return mixed
  */
  public function actionAccountStatement($id)
  {
    $this->checkSuperAdmin();
    $model=$this->findModel($id);
    $searchModel = new UserAccountsSearch();
    $searchModel->user_id=$id;
    $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

    return $this->render('account_statement', [
      'model' => $model,
      'searchModel' => $searchModel,
      'dataProvider' => $dataProvider,
    ]);
  }

	/**
	* Renew Membership
	* @param integer $id
	* @return mixed
	*/
	public function actionAddCredit($id)
	{
		$this->checkLogin();
		$model = new AddUserCredit;
		$model->user_id = $id;
		if ($model->load(Yii::$app->request->post())) {
			if($model->save()){
				echo 'success';
			}else{
				if($model->hasErrors()){
					foreach($model->getErrors() as $error){
						if(count($error)>0){
							foreach($error as $key=>$val){
								echo $val;
							}
						}
					}
				}
			}
			exit;
		}
    return $this->renderAjax('add_credit_form', [
      'model' => $model,
    ]);
	}

	/**
	* Charge Member
	* @param integer $id
	* @return mixed
	*/
	public function actionChargeCredit($id)
	{
		$this->checkLogin();
		$model = new ChargeUserCredit;
		$model->user_id = $id;
		if ($model->load(Yii::$app->request->post())) {
			if($model->save()){
				echo 'success';
			}else{
				if($model->hasErrors()){
					foreach($model->getErrors() as $error){
						if(count($error)>0){
							foreach($error as $key=>$val){
								echo $val;
							}
						}
					}
				}
			}
			exit;
		}
    return $this->renderAjax('charge_form', [
      'model' => $model,
    ]);
	}

  /**
  * Lists Security Deposit Log for User models.
  * @return mixed
  */
  public function actionSecurityDepositLog($id)
  {
    $this->checkSuperAdmin();
    $model=$this->findModel($id);
    $searchModel = new UserSecurityDepositSearch();
    $searchModel->user_id=$id;
    $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

    return $this->render('security_deposits_statement', [
      'model' => $model,
      'searchModel' => $searchModel,
      'dataProvider' => $dataProvider,
    ]);
  }

	/**
	* Add Security Deposit to Member
	* @param integer $id
	* @return mixed
	*/
	public function actionAddSecurityDeposit($id)
	{
		$this->checkLogin();
		$model = new AddSecurityDeposit;
		$model->user_id = $id;
		if ($model->load(Yii::$app->request->post())) {
			if($model->save()){
				echo 'success';
			}else{
				if($model->hasErrors()){
					foreach($model->getErrors() as $error){
						if(count($error)>0){
							foreach($error as $key=>$val){
								echo $val;
							}
						}
					}
				}
			}
			exit;
		}
    return $this->renderAjax('add_security_deposit_form', [
      'model' => $model,
    ]);
	}

	/**
	* Deduct Security Deposit for Member
	* @param integer $id
	* @return mixed
	*/
	public function actionDeductSecurityDeposit($id)
	{
		$this->checkLogin();
		$model = new DeductSecurityDeposit;
		$model->user_id = $id;
		if ($model->load(Yii::$app->request->post())) {
			if($model->save()){
				echo 'success';
			}else{
				if($model->hasErrors()){
					foreach($model->getErrors() as $error){
						if(count($error)>0){
							foreach($error as $key=>$val){
								echo $val;
							}
						}
					}
				}
			}
			exit;
		}
    return $this->renderAjax('deduct_security_deposit_form', [
      'model' => $model,
    ]);
	}

  /**
  * Finds the User model based on its primary key value.
  * If the model is not found, a 404 HTTP exception will be thrown.
  * @param integer $id
  * @return User the loaded model
  * @throws NotFoundHttpException if the model cannot be found
  */
  protected function findModel($id)
  {
    if (($model = User::findOne($id)) !== null) {
      return $model;
    }

    throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
  }
}

views/user-account/js/_scripts.php
<?php
use yii\helpers\Url;

$this->registerJs('
	$(document).delegate(".btn-add-credit", "click", function() {
		id=$(this).data("userid");
		username=$(this).data("username");
		$.ajax({
			url: "'.Url::to(['user-account/add-credit','id'=>'']).'"+id,
			dataType: "html",
			type: "POST",
			success: function(data) {
				$("#general-modal").find("h5.modal-title").html("Add Credits to "+username);
				$("#general-modal").find(".modalContent").html(data);
				$("#general-modal").modal();
			},
			error: bbAlert
		});
	});
	$("body").on("beforeSubmit", "form#user-add-credit-form", function () {
		_targetContainer=$("#user-add-credit-form")
		App.blockUI({
			message: "'.Yii::t('app','Please wait...').'",
			target: _targetContainer,
			overlayColor: "none",
			cenrerY: true,
			boxed: true
		});

		 var form = $(this);
		 // return false if form still have some validation errors
		 if (form.find(".has-error").length) {
			  return false;
		 }
		 // submit form
		 $.ajax({
			  url: form.attr("action"),
			  type: "post",
			  data: form.serialize(),
			  success: function (response) {
				  if(response=="success"){
					  swal({title: "'.Yii::t('app','Saved').'", html: "'.Yii::t('app','Credits saved successfully').'", type: "success"});
					  window.closeModal();
						$.pjax.reload({container: "#grid-container", timeout: 2000});
				  }else{
					  swal({title: "'.Yii::t('app','Error').'", html: response, type: "error"});
				  }
				  App.unblockUI($(_targetContainer));
			  }
		 });
		 return false;
	});
	$(document).delegate(".btn-charge-credit", "click", function() {
		id=$(this).data("userid");
		username=$(this).data("username");
		$.ajax({
			url: "'.Url::to(['user-account/charge-credit','id'=>'']).'"+id,
			dataType: "html",
			type: "POST",
			success: function(data) {
				$("#general-modal").find("h5.modal-title").html("Charge Credits to "+username);
				$("#general-modal").find(".modalContent").html(data);
				$("#general-modal").modal();
			},
			error: bbAlert
		});
	});
	$("body").on("beforeSubmit", "form#user-charge-form", function () {
		_targetContainer=$("#user-charge-form")
		App.blockUI({
			message: "'.Yii::t('app','Please wait...').'",
			target: _targetContainer,
			overlayColor: "none",
			cenrerY: true,
			boxed: true
		});

		 var form = $(this);
		 // return false if form still have some validation errors
		 if (form.find(".has-error").length) {
			  return false;
		 }
		 // submit form
		 $.ajax({
			  url: form.attr("action"),
			  type: "post",
			  data: form.serialize(),
			  success: function (response) {
				  if(response=="success"){
					  swal({title: "'.Yii::t('app','Saved').'", html: "'.Yii::t('app','Amount charged successfully').'", type: "success"});
					  window.closeModal();
						$.pjax.reload({container: "#grid-container", timeout: 2000});
				  }else{
					  swal({title: "'.Yii::t('app','Error').'", html: response, type: "error"});
				  }
				  App.unblockUI($(_targetContainer));
			  }
		 });
		 return false;
	});
');
?>

views/user-account/js/security_deposit_scripts.php
<?php
use yii\helpers\Url;

$this->registerJs('
	$("body").on("beforeSubmit", "form#user-add-security-deposit-form", function () {
		_targetContainer=$("#user-add-security-deposit-form")
		App.blockUI({
			message: "'.Yii::t('app','Please wait...').'",
			target: _targetContainer,
			overlayColor: "none",
			cenrerY: true,
			boxed: true
		});

		 var form = $(this);
		 // return false if form still have some validation errors
		 if (form.find(".has-error").length) {
			  return false;
		 }
		 // submit form
		 $.ajax({
			  url: form.attr("action"),
			  type: "post",
			  data: form.serialize(),
			  success: function (response) {
				  if(response=="success"){
					  swal({title: "'.Yii::t('app','Saved').'", html: "'.Yii::t('app','Security Deposit saved successfully').'", type: "success"});
					  window.closeModal();
						$.pjax.reload({container: "#grid-container", timeout: 2000});
				  }else{
					  swal({title: "'.Yii::t('app','Error').'", html: response, type: "error"});
				  }
				  App.unblockUI($(_targetContainer));
			  }
		 });
		 return false;
	});
	$("body").on("beforeSubmit", "form#user-deduct-security-deposit-form", function () {
		_targetContainer=$("#user-deduct-security-deposit-form")
		App.blockUI({
			message: "'.Yii::t('app','Please wait...').'",
			target: _targetContainer,
			overlayColor: "none",
			cenrerY: true,
			boxed: true
		});

		 var form = $(this);
		 // return false if form still have some validation errors
		 if (form.find(".has-error").length) {
			  return false;
		 }
		 // submit form
		 $.ajax({
			  url: form.attr("action"),
			  type: "post",
			  data: form.serialize(),
			  success: function (response) {
				  if(response=="success"){
					  swal({title: "'.Yii::t('app','Saved').'", html: "'.Yii::t('app','Amount deducted from Security Deposit successfully').'", type: "success"});
					  window.closeModal();
						$.pjax.reload({container: "#grid-container", timeout: 2000});
				  }else{
					  swal({title: "'.Yii::t('app','Error').'", html: response, type: "error"});
				  }
				  App.unblockUI($(_targetContainer));
			  }
		 });
		 return false;
	});
');
?>