models/OperationRequests.php
<?php

namespace app\models;

use Yii;
use yii\db\ActiveRecord;
use yii\behaviors\TimestampBehavior;
use yii\behaviors\BlameableBehavior;
use app\components\behaviors\ActivityLogBehaviorUser;

/**
* This is the model class for table "{{%operations_requests}}".
*
* @property integer $id
* @property integer $boat_id
* @property string $req_type
* @property integer $req_id
* @property integer $completed
* @property string $created_at
* @property integer $created_by
* @property string $updated_at
* @property integer $updated_by
*/
class OperationRequests extends ActiveRecord
{
  /**
  * @inheritdoc
  */
  public static function tableName()
  {
    return '{{%operations_requests}}';
  }

  /**
  * @inheritdoc
  */
  public function rules()
  {
    return [
      [['boat_id', 'req_type', 'req_id'], 'required'],
      [['boat_id', 'req_id', 'completed', 'created_by', 'updated_by'], 'integer'],
      [['completed_date', 'created_at', 'updated_at'], 'safe'],
      [['req_type'], 'string', 'max' => 3],
    ];
  }

  /**
  * @inheritdoc
  */
  public function attributeLabels()
  {
    return [
      'id' => Yii::t('app', 'ID'),
      'boat_id' => Yii::t('app', 'Boat ID'),
      'req_type' => Yii::t('app', 'Req Type'),
      'req_id' => Yii::t('app', 'Req ID'),
      'completed' => Yii::t('app', 'Completed'),
      'created_at' => Yii::t('app', 'Created At'),
      'created_by' => Yii::t('app', 'Created By'),
      'updated_at' => Yii::t('app', 'Updated At'),
      'updated_by' => Yii::t('app', 'Updated By'),
    ];
  }

  /**
  * @inheritdoc
  */
  public function behaviors()
  {
    return [
      'timestamp' => [
        'class' => TimestampBehavior::className(),
        'attributes' => [
          ActiveRecord::EVENT_BEFORE_INSERT => ['created_at','updated_at'],
          ActiveRecord::EVENT_BEFORE_UPDATE => 'updated_at',
        ],
        'value' => function($event) {
          return date("Y-m-d H:i:s");
        },
      ],
      'blameable' => [
        'class' => BlameableBehavior::className(),
        'createdByAttribute' => 'created_by',
        'updatedByAttribute' => 'updated_by',
      ],
      'LoggableBehavior' => [
        'class' => ActivityLogBehaviorUser::className(),
      ],
    ];
  }

  /**
  * @return \yii\db\ActiveQuery
  */
  public function getCreatedByUser()
  {
    return $this->hasOne(User::className(), ['id' => 'created_by']);
  }

  /**
  * @return string, name of user
  */
  public function getCreatedBy()
  {
    if($this->createdByUser!=null){
      return $this->createdByUser->fullname;
    }
  }

  /**
  * @return \yii\db\ActiveQuery
  */
  public function getUpdatedByUser()
  {
    return $this->hasOne(User::className(), ['id' => 'updated_by']);
  }

  /**
  * @return string, name of user
  */
  public function getUpdatedBy()
  {
    if($this->updatedByUser!=null){
      return $this->updatedByUser->fullname;
    }
  }

  /**
  * @return \yii\db\ActiveQuery
  */
  public function getRequestDetail()
  {
    if($this->req_type=='S'){
      return RequestService::findOne($this->req_id);
    }elseif($this->req_type=='BD'){
      return RequestBreakDown::findOne($this->req_id);
    }elseif($this->req_type=='I'){
      return RequestInspection::findOne($this->req_id);
    }
  }

  public function getLevel()
  {
    if($this->req_type=='BD'){
      return $this->requestDetail->break_down_level=='maj' ? 'Major' : 'Minor';
    }
  }

  public function getDescp()
  {
    if($this->req_type=='BD'){
      return $this->requestDetail->description;
    }
  }

  /**
  * @return \yii\db\ActiveQuery
  */
  public function getBoat()
  {
    return $this->hasOne(Boat::className(), ['id' => 'boat_id']);
  }
}

controllers/OperationRequestsController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use app\components\helpers\DefController;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\RequestService;
use app\models\RequestServiceSearch;
use app\models\RequestBreakDown;
use app\models\RequestBreakDownSearch;
use app\models\RequestInspection;
use app\models\RequestInspectionSearch;

class OperationRequestsController extends DefController
{
  /**
  * {@inheritdoc}
  */
  public function behaviors()
  {
    return [
      'access' => [
        'class' => AccessControl::className(),
        'only' => ['service','inspection','inspection-detail'],
        'rules' => [
          [
            'actions' => ['service','inspection','inspection-detail'],
            'allow' => true,
            'roles' => ['@'],
          ],
        ],
      ],
    ];
  }

  /**
  * Lists all Requests models.
  * @return mixed
  */
  public function actionService()
  {
    $this->checkAdmin();

    $searchModel = new RequestServiceSearch();
    if(Yii::$app->user->identity->user_type!=1){
      $searchModel->status=0;
      $searchModel->created_by=Yii::$app->user->identity->id;
    }
    $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

    return $this->render('service', [
      'dataProvider' => $dataProvider,
      'searchModel' => $searchModel,
    ]);
  }

  /**
  * Lists all Requests models.
  * @return mixed
  */
  public function actionBreakDown()
  {
    $this->checkAdmin();
    $searchModel = new RequestBreakDownSearch();
    if(Yii::$app->user->identity->user_type!=1){
      $searchModel->status=0;
      $searchModel->created_by=Yii::$app->user->identity->id;
    }
    $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

    return $this->render('break_down', [
      'dataProvider' => $dataProvider,
      'searchModel' => $searchModel,
    ]);
  }

  /**
  * Lists all Requests models.
  * @return mixed
  */
  public function actionInspection()
  {
    $this->checkAdmin();

    $searchModel = new RequestInspectionSearch();
    if(Yii::$app->user->identity->user_type!=1){
      $searchModel->created_by=Yii::$app->user->identity->id;
    }
    $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

    return $this->render('inspection', [
      'dataProvider' => $dataProvider,
      'searchModel' => $searchModel,
    ]);
  }

  public function actionInspectionDetail($id)
  {
    $this->checkAdmin();
    $this->layout = 'ajax';
    $model=$this->findInspectionModel($id);
    if($model!=null){
      return $this->renderAjax('_inspection_items_detail', [
        'model' => $model,
      ]);
    }
  }

  /**
  * Finds the RequestService model based on its primary key value.
  * If the model is not found, a 404 HTTP exception will be thrown.
  * @param integer $id
  * @return RequestService the loaded model
  * @throws NotFoundHttpException if the model cannot be found
  */
  protected function findServiceModel($id)
  {
    if (($model = RequestService::findOne($id)) !== null) {
      return $model;
    } else {
      throw new NotFoundHttpException('The requested page does not exist.');
    }
  }

  /**
  * Finds the RequestBreakDown model based on its primary key value.
  * If the model is not found, a 404 HTTP exception will be thrown.
  * @param integer $id
  * @return RequestBreakDown the loaded model
  * @throws NotFoundHttpException if the model cannot be found
  */
  protected function findBreakDownModel($id)
  {
    if (($model = RequestBreakDown::findOne($id)) !== null) {
      return $model;
    } else {
      throw new NotFoundHttpException('The requested page does not exist.');
    }
  }

  /**
  * Finds the RequestBreakDown model based on its primary key value.
  * If the model is not found, a 404 HTTP exception will be thrown.
  * @param integer $id
  * @return RequestBreakDown the loaded model
  * @throws NotFoundHttpException if the model cannot be found
  */
  protected function findInspectionModel($id)
  {
    if (($model = RequestInspection::findOne($id)) !== null) {
      return $model;
    } else {
      throw new NotFoundHttpException('The requested page does not exist.');
    }
  }
}

views/operation-requests/_inspection_items_detail.php
<?php
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\RequestInspection */
?>
<div class="inspection-items-list">
	<div class="row">
		<div class="col-sm-12"><h4><?= $model->boat->name?></h4></div>
	</div>
	<table class="table table-striped">
		<thead>
			<tr>
				<th width="10">#</th>
				<th>Items to check</th>
				<th>Conditions & Availability</th>
				<th>Remarks & Inquiries</th>
			</tr>
		</thead>
		<tbody>
			<?php
			$n=1;
			$inspectionItems=$model->inspectionItems;
			if($inspectionItems!=null){
				foreach($inspectionItems as $item){
					?>
					<tr>
						<td><?= $n?></td>
						<td><?= $item->item->title?></td>
						<td><?= $item->item_condition?></td>
						<td><?= $item->item_comments?></td>
					</tr>
					<?php
					$n++;
				}
			}
			?>
		</tbody>
	</table>
</div>

views/operation-requests/break_down.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use app\components\widgets\CustomGridView;
use app\components\widgets\CustomPjax;
use app\assets\BreakdownRequestAssets;
BreakdownRequestAssets::register($this);

/* @var $this yii\web\View */
/* @var $searchModel app\models\RequestBreakDownSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Breakdown');
$this->params['breadcrumbs'][] = Yii::t('app', 'Operation Reports');
$this->params['breadcrumbs'][] = $this->title;


$columns[]=['class' => 'yii\grid\SerialColumn'];
$columns[]=['attribute'=>'boat_id','value'=>function($model){
	return $model['boat_name'];
},'filter'=>Yii::$app->appHelperFunctions->getBoatsListArr()];
$columns[]='description';
$columns[]=['label'=>Yii::t('app','Level'),'attribute'=>'break_down_level','value'=>function($model){
	return Yii::$app->operationHelperFunctions->breakDownLevel[$model['break_down_level']];
},'filter'=>Yii::$app->operationHelperFunctions->breakDownLevel];
$columns[]=['format'=>'html','label'=>'Reason','attribute'=>'reason','value'=>function($model){
	return Yii::$app->operationHelperFunctions->breakDownReason[$model['reason']];
},'filter'=>Yii::$app->operationHelperFunctions->breakDownReason];
$columns[]=['format'=>'html','label'=>'Member Remarks','attribute'=>'user_remarks','value'=>function($model){
	return $model['user_remarks'];
}];
$columns[]=['format'=>'date','label'=>Yii::t('app','Date'),'attribute'=>'req_date','filterInputOptions'=>['class'=>'form-control dtpicker','autocomplete'=>'off']];
if(Yii::$app->user->identity->user_type==1){
	$columns[]=['format'=>'html','label'=>Yii::t('app','Status'),'attribute'=>'status','value'=>function($model){
		return Yii::$app->operationHelperFunctions->requestStatusIcon[$model['status']];
	},'filter'=>Yii::$app->operationHelperFunctions->requestStatus];
	$columns[]='admin_remarks';
	$columns[]=['format'=>'date','label'=>Yii::t('app','Action Date'),'attribute'=>'admin_action_date','filterInputOptions'=>['class'=>'form-control dtpicker','autocomplete'=>'off']];
}

$actionBtns='';
if(Yii::$app->menuHelperFunction->checkActionAllowed('update','request-break-down')){
	$actionBtns.='{update}';
}
if(Yii::$app->menuHelperFunction->checkActionAllowed('change-status','request-break-down')){
	$actionBtns.='{change-status}';
}
if(Yii::$app->menuHelperFunction->checkActionAllowed('admin-remarks','request-break-down')){
	$actionBtns.='{admin-remarks}';
}
$columns[]=[
	'class' => 'yii\grid\ActionColumn',
	'header'=>'Actions',
	'headerOptions'=>['class'=>'noprint','style'=>'width:10px;'],
	'contentOptions'=>['class'=>'noprint nsd'],
	'template' => '
	<div class="btn-group flex-wrap">
	<button type="button" class="mb-1 mt-1 mr-1 btn btn-xs btn-default dropdown-toggle" data-toggle="dropdown">
	<span class="caret"></span>
	</button>
	<div class="dropdown-menu" role="menu">
	'.$actionBtns.'
	</div>
	</div>',
	'buttons' => [
		'update' => function ($url, $model) {
			if($model['status']==0){
				return Html::a('<i class="fas fa-edit"></i> Update', 'javascript:;', [
					'class'=>'dropdown-item text-1 load-modal',
					'data-url'=>Url::to(['request-break-down/update','id'=>$model['id']]),
					'data-heading' => Yii::t('app', 'Update Request'),
					'data-pjax'=>"0",
				]);
			}
		},
		'change-status' => function ($url, $model) {
			if($model['status']==0){
				return Html::a('<i class="fas fa-check"></i> Done', 'javascript:;', [
					'class'=>'dropdown-item text-1 change-status',
					'data-id'=>$model['id'],
					'data-title'=>'Done',
					'data-status'=>2,
				]).
				Html::a('<i class="fas fa-times"></i> Cancelled', 'javascript:;', [
					'class'=>'dropdown-item text-1 change-status',
					'data-id'=>$model['id'],
					'data-title'=>'Cancelled',
					'data-status'=>1,
				]);
			}
		},
		'admin-remarks' => function ($url, $model) {
			return Html::a('<i class="fas fa-edit"></i> Remarks', 'javascript:;', [
				'class'=>'dropdown-item text-1 load-modal',
				'data-url'=>Url::to(['request-break-down/admin-remarks','id'=>$model['id']]),
				'data-heading' => Yii::t('app', 'Remarks'),
				'data-pjax'=>"0",
			]);
		},
	],
];
?>
<?php CustomPjax::begin(['id'=>'grid-container']); ?>
<?= CustomGridView::widget([
  'dataProvider' => $dataProvider,
  'filterModel' => $searchModel,
  'columns' => $columns,
  'layout'=>"{items}<div>{summary}</div><div>{pager}</div>",
]); ?>
<?php CustomPjax::end(); ?>
<?= $this->render('js/breakdown_scripts')?>
<?= $this->render('/request-break-down/js/request_breakdown_scripts')?>

views/operation-requests/inspection.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use app\components\widgets\CustomGridView;
use app\components\widgets\CustomPjax;
use app\assets\InspectionRequestAssets;
InspectionRequestAssets::register($this);

/* @var $this yii\web\View */
/* @var $searchModel app\models\RequestInspectionSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Inspections');
$this->params['breadcrumbs'][] = Yii::t('app', 'Operation Reports');
$this->params['breadcrumbs'][] = $this->title;

$this->registerJs('
	initDatePicker();
	$(document).on("pjax:success", function() {
		initDatePicker();
	});
');
$columns[]=['class' => 'yii\grid\SerialColumn'];
$columns[]=['attribute'=>'boat_id','value'=>function($model){
	return $model['boat_name'];
},'filter'=>Yii::$app->appHelperFunctions->getBoatsListArr()];
$columns[]=['attribute'=>'inspection_date','format'=>'date','label'=>Yii::t('app','Date'),'value'=>function($model){
	return $model['inspection_date'];
},'filterInputOptions'=>['class'=>'form-control dtpicker','autocomplete'=>'off']];
$columns[]='remarks';
$columns[]=['format'=>'raw','label'=>Yii::t('app','Items'),'value'=>function($model){
	return Html::a('View Items','javascript:;',['class'=>'load-modal','data-heading'=>'Inspection Items','data-url'=>Url::to(['inspection-detail','id'=>$model['id']])]);
}];
?>
<?php CustomPjax::begin(); ?>
<?= CustomGridView::widget([
  'dataProvider' => $dataProvider,
  'filterModel' => $searchModel,
  'columns' => $columns,
  'layout'=>"{items}<div>{summary}</div><div>{pager}</div>",
]); ?>
<?php CustomPjax::end(); ?>
<script>
function initDatePicker()
{
	$(".dtpicker").datepicker({
		format: "yyyy-mm-dd",
	}).on("changeDate", function(e){
		$(this).datepicker("hide");
	});
}
</script>

views/operation-requests/service.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use app\components\widgets\CustomGridView;
use app\components\widgets\CustomPjax;
use app\assets\ServiceRequestAssets;
ServiceRequestAssets::register($this);

/* @var $this yii\web\View */
/* @var $searchModel app\models\RequestServiceSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Service Report');
$this->params['breadcrumbs'][] = Yii::t('app', 'Operation Reports');
$this->params['breadcrumbs'][] = $this->title;

$colums[]=['class' => 'yii\grid\SerialColumn'];
$colums[]=['attribute'=>'boat_id','value'=>function($model){
	return $model['boat_name'];
},'filter'=>Yii::$app->appHelperFunctions->getBoatsListArr()];
$colums[]='current_hours';
$colums[]='scheduled_hours';
$colums[]=['format'=>'date','label'=>Yii::t('app','Date'),'attribute'=>'req_date','filterInputOptions'=>['class'=>'form-control dtpicker','autocomplete'=>'off']];
$colums[]='remarks';
if(Yii::$app->user->identity->user_type==1){
	$colums[]=['format'=>'html','label'=>Yii::t('app','Status'),'attribute'=>'status','value'=>function($model){
		return Yii::$app->operationHelperFunctions->requestStatusIcon[$model['status']];
	},'filter'=>Yii::$app->operationHelperFunctions->requestStatus];
	$colums[]='admin_remarks';
	$colums[]=['format'=>'date','label'=>Yii::t('app','Action Date'),'attribute'=>'admin_action_date','filterInputOptions'=>['class'=>'form-control dtpicker','autocomplete'=>'off']];
}

$actionBtns='';
if(Yii::$app->menuHelperFunction->checkActionAllowed('update','request-service')){
	$actionBtns.='{update}';
}
if(Yii::$app->menuHelperFunction->checkActionAllowed('change-status','request-service')){
	$actionBtns.='{change-status}';
}
if(Yii::$app->menuHelperFunction->checkActionAllowed('admin-remarks','request-service')){
	$actionBtns.='{admin-remarks}';
}
$colums[]=[
	'class' => 'yii\grid\ActionColumn',
	'header'=>'Actions',
	'headerOptions'=>['class'=>'noprint','style'=>'width:10px;'],
	'contentOptions'=>['class'=>'noprint nsd'],
	'template' => '
	<div class="btn-group flex-wrap">
	<button type="button" class="mb-1 mt-1 mr-1 btn btn-xs btn-default dropdown-toggle" data-toggle="dropdown">
	<span class="caret"></span>
	</button>
	<div class="dropdown-menu" role="menu">
	'.$actionBtns.'
	</div>
	</div>',
	'buttons' => [
		'update' => function ($url, $model) {
			if($model['status']==0){
				return Html::a('<i class="fas fa-edit"></i> Update', 'javascript:;', [
					'class'=>'dropdown-item text-1 load-modal',
					'data-url'=>Url::to(['request-service/update','id'=>$model['id']]),
					'data-heading' => Yii::t('app', 'Update Request'),
					'data-pjax'=>"0",
				]);
			}
		},
		'change-status' => function ($url, $model) {
			if($model['status']==0){
				return Html::a('<i class="fas fa-check"></i> Done', 'javascript:;', [
					'class'=>'dropdown-item text-1 change-status',
					'data-id'=>$model['id'],
					'data-title'=>'Done',
					'data-status'=>2,
				]).
				Html::a('<i class="fas fa-times"></i> Cancelled', 'javascript:;', [
					'class'=>'dropdown-item text-1 change-status',
					'data-id'=>$model['id'],
					'data-title'=>'Cancelled',
					'data-status'=>1,
				]);
			}
		},
		'admin-remarks' => function ($url, $model) {
			return Html::a('<i class="fas fa-edit"></i> Remarks', 'javascript:;', [
				'class'=>'dropdown-item text-1 load-modal',
				'data-url'=>Url::to(['request-service/admin-remarks','id'=>$model['id']]),
				'data-heading' => Yii::t('app', 'Remarks'),
				'data-pjax'=>"0",
			]);
		},
	],
];
?>

<?php CustomPjax::begin(['id'=>'grid-container']); ?>
<?= CustomGridView::widget([
	'dataProvider' => $dataProvider,
	'filterModel' => $searchModel,
	'columns' => $colums,
	'layout'=>"{items}<div>{summary}</div><div>{pager}</div>",
]); ?>
<?php CustomPjax::end(); ?>
<?= $this->render('js/service_scripts')?>
<?= $this->render('/request-service/js/request_service_scripts')?>